### ISSUE TITLE
Am I setting it up wrong?

### ISSUE THREAD

**Issue by maxobremer** [p4535992/conditional-visibility#20]
Hi I have a question
I have a player with devil's sight so wanted use this so that he can see hidden creatres, but when creature is In Darkness (CV) the pc with devils sight still cant see it? 
I tried adding devilsight to the In Darkness (CV) DAE and that worked, so i have two questions
I tried making the "ATCV.indarkness" to custom with the effect value "data.skills.ste.passive" so it would use the passive stealth, which didnt work, how do i make this work?
Is it possible to have people with dark vision see stuff "In Dark" but with a -5 to their perception or +to the hidden creature's stealth, since theyd get disadvantage?

Is it also possible to have a dim light in addition of In Darkness (CV) option?

**Comment by p4535992** [comment]
**_I have a player with devil's sight so wanted use this so that he can see hidden creatres, but when creature is In Darkness (CV) the pc with devils sight still cant see it?_**

i will make some test and let you know if is a bug

**_tried making the "ATCV.indarkness" to custom with the effect value "data.skills.ste.passive" so it would use the passive stealth, which didnt work, how do i make this work?_**

a ok didn't think of this use case, but it is not to hard to integrated. i'll try to put this feature in the next release , so you can just set the active effect: `ATCV.indarkness=data.skills.ste.passive` or  `ATCV.indarkness=data.skills.ste.passive - 5` ,  (this will be system dependent)

**_Is it possible to have people with dark vision see stuff "In Dark" but with a -5 to their perception or +to the hidden creature's stealth, since theyd get disadvantage?_**

i have no idea how to do this... you can use `ATCV.indarkness=data.skills.ste.passive - 5`  (on the next release) but not sure if is it enough for your use case.

**Is it also possible to have a dim light in addition of In Darkness (CV) option?_**

ok here I'm still thinking about how to manage it to make it even more automated, the concept for the moment is that I don't want to rewrite the ATE code in my module, so for now the solution is to add the following changes to the effect:
`ATL.light.dim=30`

**Comment by p4535992** [comment]
**_I have a player with devil's sight so wanted use this so that he can see hidden creatres, but when creature is In Darkness (CV) the pc with devils sight still cant see it?_**

Solved with 0.5.5

**_tried making the "ATCV.indarkness" to custom with the effect value "data.skills.ste.passive" so it would use the passive stealth, which didnt work, how do i make this work?_**

Solved with 0.5.5

**_Is it possible to have people with dark vision see stuff "In Dark" but with a -5 to their perception or +to the hidden creature's stealth, since theyd get disadvantage?_**

Solved with 0.5.6 , should support all the formula supported from the foundryvtt system

**Is it also possible to have a dim light in addition of In Darkness (CV) option?_**

Not solved Just use standard ATL

**Comment by maxobremer** [comment]
Hi,

Just updated to 0.5.6 and noticed something a hidden creature is invisible for someone with any kind of sight added. Like if they do NOT have devil sight or darkvision and do have a high enough passive then they're visible but someone with the same passive perception and darkvision or devil sight or see invisible can NOT see them

Did a bit of a bigger test and this is passive perception of 18 vs stealth of 17
![image](https://user-images.githubusercontent.com/86924581/159965388-c0d38a13-fbff-4d42-ab17-c0c6d1d1d803.png)
each group is what the guy at the bottom can see
yellow has no added sight in any way, just a dude
blue is a blinded and a darkvision guy
red is a devils sight and a darkvision+devils sight guy
green is  a true sight and a see invisibility guy
yellow is a tremor sense and a blindsight guy

now for the hiders we have
yellow has no added sight in any way, just a dude
blue is a nothing
red is a in dark feline stalker
green is  a invisible feline stalker
yellow is a in dark, invisible and a obscured feline stalker

all hiders/feline stalkers are only visible for the guys in the same coloured square


I would expect truesight to see all the feline stalkers, I would expect every guy to see the hidden feline stalker and id expect some more from the darkvision guy who cant even see a in dark value of 10, which RAW dnd 5e is should

**Comment by maxobremer** [comment]
Btw thanks for the responses and work up till now


another question i had was if it was possible to have a value to determine the range of certain visions, like someone with tremor sense can see less far the most with darkvision, not always but most of the time. would also be nice if the effect looks at the senses section of a characters sheet to determine if they have a certain vision and out to which range

**Comment by p4535992** [comment]
wow thanks, the test must have taken you some time.

**_I would expect truesight to see all the feline stalkers,_**

for how i have prepared the default values on the [dnd5e table](https://github.com/p4535992/conditional-visibility/blob/master/wiki/table_dnd5e.md), _true sight_ can see _invisible_ and _in darkness_ , but not _obscured_ targets do you think this is a mistake on my part?

but if you want you can customize this with the `ATCV.condtionTargets` on the source token active effect. 

_true sight_ should see the token with the condition of _in darkness_ . Is the numeric value assigned to the _in darkness_ effect greater than that assigned to _true sight_? Because this would explain the behavior and would be correct.

the module as described in the documentation have two main controls:
1) the _sense_ can see the _condition_ (check out the table)
2) the value assigned to the _sense_ is >= the one assigned to the _condition_

**_I would expect every guy to see the hidden feline stalker and id expect some more from the darkvision guy who cant even see a in dark value of 10, which RAW dnd 5e is should_**

Ok the token with darkvision should see the "cat" if the value of the _hidden_ <= to the passive perception of the token, that can be a bug...i will checkout

The darkvision is something I have to work a little bit on to synchronize it with the new ATE released 1 day ago and better integration with PV, you can always customize as you like the actiev effect by adding / removing the various _active effect changes_ of both CV and of ATL.

For your use case maybe you want to add a `conditionDistance = 10` to be able to see creatures with a value of _hidden_ <= to the CV value associated with darkvision

**_another question i had was if it was possible to have a value to determine the range of certain visions, like someone with tremor sense can see less far the most with darkvision, not always but most of the time._**

you mean the `conditionDistance` feature ?
![conditionDistance](https://raw.githubusercontent.com/p4535992/conditional-visibility/master/wiki/video/feature_distance.gif)

**_would also be nice if the effect looks at the senses section of a characters sheet to determine if they have a certain vision and out to which range_**

I can try to develop a code that reads the senses of the actor and that auto-generates the _active effect change_ `conditionDistance` which represents the effect distance of the sense, do you think this is the correct solution?

**Comment by p4535992** [comment]
i think with the version 0.5.24 these issues shoudl be solved, at least for me but let me know it.
